---
- hosts: redis_nodes
  become: true
  roles:
    - asnm_redis

- hosts: redis_cluster
  become: true
  roles:
    - asnm_redis

- name: another play
  hosts: prometheus
  become: true
  tasks:
    - include: asnm_redis/tasks/prometheus.yaml
