---
- name: Copy redis.service file to redis server
  template:
    src: redis.service.j2
    dest: "/etc/systemd/system/redis.service"
    owner: root
    group: root
  notify:
    - Reload systemd daemon

- name: Copy redis.conf to redis server
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_file_location }}/redis.conf"
    owner: redis
    group: redis
  notify:
    - Start Redis Service
